name: hello-Nick
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: run app
        run: echo "Hello Hartree and Nick!"
      - name: check out
        uses: actions/checkout@v3
